### ISSUE TITLE
Backspace when typing commands or searching not working

### ISSUE THREAD

**Issue by mbarbar** [krpors/hx#15]
Not sure if it's just my machine or not... backspace does not seem to work. Changing KEY_BACKSPACE to 0x08 (\b in the ASCII table actually) seems to work fine for me.

**Comment by krpors** [comment]
What terminal do you use? And what is your `$TERM` variable? When I use `0x08` I can only delete characters when I press `CTRL+H`. I'm using `urxvt` myself. I also tried it with `xfce4-terminal` and that one seems to work too. I think it's something to do with the termcaps. 

Anyway, the kilo editor also maps Ctrl+H and backspace as one key so it's an easy patch I suppose: Add `KEY_CTRL_H` with value `0x08` in util.h, then add a case statement in util.c:

      case KEY_BACKSPACE:
      case KEY_CTRL_H:
          return KEY_BACKSPACE;
      }

**Comment by mbarbar** [comment]
Should've mentioned that. I'm on xterm (version 330). Maybe a bit outdated haha.

I can commit (and test) that and make a PR later today if you haven't added it in already by then.

**Comment by krpors** [comment]
Fixed in commit dde5152809.
