### ISSUE TITLE
Your project was stolen

### ISSUE THREAD

**Issue by AlexZolcman** [krpors/hx#22]
Good afternoon!

I would like to inform you that this project has been stolen:

https://5ht.github.io/be/ ([archived](https://web.archive.org/web/20220602170803/https://5ht.github.io/be/))

https://github.com/5HT/be/blob/main/editor.c#L16 ([archived](https://web.archive.org/web/20220602170809/https://github.com/5HT/be/blob/main/editor.c)) ([fork](https://github.com/VladimirEpifancev/be/blob/main/editor.c#L23))

https://github.com/krpors/hx/blob/develop/editor.c#L95

Well, and many other facts indicating that the code was completely copied 
(of course, with the [authorship erased](https://github.com/5HT/be/blob/main/LICENSE))

(all his development is renaming functions and shuffling lines of code)

This person stole code from many people and then presented it as his own projects. 
My good fellow was in a similar situation himself when all his work was stolen by @5HT.

It's up to you to decide what to do with this information.

**Comment by krpors** [comment]
Thank you for this notice.

Is this some sort of template message by the way? I got somewhat the same text from an entire different person on the same day.

**Comment by 5HT** [comment]
They have special russian channel where they prepare such attacks on me all over the internet.

**Comment by krpors** [comment]
Weird. Anyway I appreciate the mention on `be`. It's looking good :)

**Comment by AlexZolcman** [comment]
Do not believe this person.

He will never continue further development of your project, all he will do is rename some functions, change the order of some lines of code, maybe split some files into several ones. After a while he will rename the project and your name in the README won't be there anymore. 

As I wrote above, this person did a lot of damage to a fellow I know, so I don't want anyone else to get hurt by him.

You can check out [our little investigation](https://gist.github.com/forked-from-1kasper/06d241303cc314b35c291c38e61a5e0c), as well as [this](https://twitter.com/siegment/status/1512078320732573713) and [this](https://twitter.com/siegment/status/1512800681844953088) thread on Twitter, to form an opinion about this person.

Again, it is your right to decide what to do with this information.
I just don't want this person to build his career on a lot of lies and other people's work.

P.S.

My Google account is not under my real last name for privacy reasons.

**Comment by 5HT** [comment]
I have one question for you, who take down MH-17?

**Comment by AlexZolcman** [comment]
Right now Maxim Sokhatsky (@5HT) already has the nerve to write that he himself wrote the be in three days:

> The only thing left is scrolling in disassembler mode and HEX editing in the same mode. It’s possible to write a disassembler-editor in 3 days.

https://twitter.com/infinitystack/status/1533619132733833222
([archived version](https://web.archive.org/web/20220606040440/https://twitter.com/infinitystack/status/1533619132733833222
))

> Who can't write a disassembler in 3 days, I'll take away his degree in programming!

https://twitter.com/infinitystack/status/1533619439094177797
([archived version](https://web.archive.org/web/20220606040634/https://twitter.com/infinitystack/status/1533619439094177797))

You can check the content of these tweets with any adequate translation service.

The fact that it's his account he himself indicated in the description:

> @5HT Maxim Sokhatsky's personal account.

([archived](https://web.archive.org/web/20220606040847/https://twitter.com/infinitystack))

**Comment by AlexZolcman** [comment]
@5HT claimed that he changed the license because he couldn't allow anyone from Russia to use «his» project, while, in fact, he only changed the license of your project hx, but not the license of the code from the NASM authors

https://github.com/5HT/be/blob/main/x86/bytesex.h

And the reasons are clear: NASM has a large community, so it will be much easier to catch him stealing code. This is why he doesn't even try to change the license of the code he took from the NASM repository. 

Your project is not that big, so he thinks that he can easily get away with blatantly copying the code and then erasing the copyright.

**Comment by 5HT** [comment]
Very funny chat, I'm just waiting for @krpors resolution :-)

**Comment by 5HT** [comment]
@AlexZolcman I tell you more. `be` will have the plugin system and I could steal GPL code from russian `beye` even and make a perfect legal module :-) Will you report me on beye then? I need some inception there too! Seem you guys in your russian village have no idea about how software is produced. I promise I will report timing of implementing GPL-ed stolen plugins too. So you should expect even more blatant and nerve claims, not sure you consiousness could handle that.

**Comment by AlexZolcman** [comment]
> I could steal GPL code from russian beye even and make a perfect legal module :-)

No, you can't.
Incorporating or linking against GPL requires that your project-as-a-whole be distributed under GPL.

> Seems you guys in your russian village have no idea about how software is produced. 

Please, don't jump to insults.

**Comment by 5HT** [comment]
Do you know how plugins of foobar2000 and FAR are being licensed?

**Comment by 5HT** [comment]
`be` is going to be epic, `hx` will remain in heritage. No matter what ruscists sponsoring terrorism think about linking GPL plugins with proprietary code.

**Comment by AlexZolcman** [comment]
> Do you know how plugins of foobar2000 and FAR are being licensed? If you don't want insults please answer then who took down MH-17? Seems like your whole text stream is going to be insult to someone.

GPL-licensed plugins or modules must have a special statement giving blanket permission to link with non-free software. 

As an example of this kind of permission, consider the [Guile license](https://www.gnu.org/software/guile/docs/docs-1.6/guile-ref/Guile-License.html).

Beye is licensed without any additional permissions

> Not sure what you want to achieve here.

I just don't want you to keep parasitizing other people's work. 

> civilised world at Github.

This contradicts [your own post](https://tonpa.guru/stream/2022/2022-03-15%20Github%20supports%20Russian%20Fascism.htm).

> ruscists sponsoring terrorism

@5HT, you have sent numerous donations to developers in Russia to develop various projects (_and then appropriated these projects to yourself_). The existence of these donations is easy to check in the banking system


Consider your license:

> YOU CANNOT USE THIS SOFTWARE IN ANY (PROVABLE BY MONEY TRACE) PROCESS CHAIN OF EXTERMINATING UKRAINIANS

And also recall your explicit belief that paying taxes on the territory of the Russian Federation is sponsorship of the Russian regime. 

It follows that you yourself, to some extent, sponsored the Russian regime, and therefore you have no right to use the software that you yourself have licensed under the DHARMA license.

Perhaps your license needs some improvement?

**Comment by AlexZolcman** [comment]
> Yes, according to russian I should kill myself. I know.

But it follows from your own license.

**Comment by 5HT** [comment]
ok so we done here?

**Comment by 5HT** [comment]
or I should eat more russian bullshit today?

**Comment by 5HT** [comment]
I really hate this thread and attacks. A perfect example that russians should be banned at Github.

**Comment by AlexZolcman** [comment]
> I really hate this thread and attacks. A perfect example that russians should be banned at Github.

All I want is for you to respect the licenses and principles of the Open Source community. 
So that you stop copying other people's code without attribution.

And for God's sake, let's not use insults against me.
After all, I'm talking to you in a civilized way.

**Comment by 5HT** [comment]
You want him to change his mind?

**Comment by 5HT** [comment]
Selling stalking as civilized discussion with yellow titles this is beyond my understanding of open source standards.

**Comment by 5HT** [comment]
The only person who can’t outlive it is a person who recieved a bunch of money from me, and after full scale invasion called me khohol saying its normal, being my student. That is the russian understanding of open source and its ethics.

**Comment by 5HT** [comment]
Also it is funny that you spend more time on putting shit in this thread than I spent on editor.

**Comment by AlexZolcman** [comment]
> Also it is funny that you spend more time on putting shit in this thread than I spent on editor.

Because you didn't write “be”, you just copied it.

**Comment by 5HT** [comment]
Ok go write that @5HT thief on the wall of your toilet. You already did that. How many times you want to repeat it here?

**Comment by 5HT** [comment]
Do you understand that even if I put MIT license of hx in repository you still will not be able to use be legally?

**Comment by AlexZolcman** [comment]
> Do you understand that even if I put MIT license of hx in repository you still will not be able to use be legally?

What? Why?

**Comment by 5HT** [comment]
Aha, you like it. Just want to use :-) Because I will put license on my files that will prohibit this.

**Comment by 5HT** [comment]
Most ridiculous imbecile I ever met at Github.

**Comment by 5HT** [comment]
So you think that if SONY TV is using MIT licensed library you should open source SONY TV under MIT license or what ?

**Comment by 5HT** [comment]
I think @krpors you could close this bullshit freely: https://github.com/5HT/be/tree/main/licenses

**Comment by AlexZolcman** [comment]
> Aha, you like it. Just want to use :-) 

No, I'm just wondering how you can legally ban certain people from using software under free license.

> So you think that if SONY TV is using MIT licensed library you should open source SONY TV under MIT license or what?

In that case, as I understand it, your license is not free.

> I think @krpors you could close this bullshit freely

Format your license file, [like here](https://github.com/minetest/minetest/blob/master/LICENSE.txt). 
One file, with hx, NASM, and your license.

**Comment by 5HT** [comment]
I added this incident to a list of examples of russian stupidity: https://tonpa.guru/stream/2022/2022-04-10%20Russian%20War%20against%20Groupoid%20Infinity.htm

**Comment by 5HT** [comment]
> Format your license file, [like here](https://github.com/minetest/minetest/blob/master/LICENSE.txt).

You'd better go to university, learn some scientific communism.

**Comment by AlexZolcman** [comment]
> > Format your license file, [like here](https://github.com/minetest/minetest/blob/master/LICENSE.txt).
> 
> You'd better go to university, learn some scientific communism.

Please, all I ask is for the licensing to be done correctly. 
I gave you an example, what's the problem?

**Comment by 5HT** [comment]
This is not a license requirement. Go to school kid.

**Comment by AlexZolcman** [comment]
Don't try to hide licenses away. 
Why are you so reluctant to license “be” correctly?

**Comment by 5HT** [comment]
I stole `hx` by putting license in folder. Period.

**Comment by AlexZolcman** [comment]
What you've done is not any more or less correct. 
From a legitimate point of view, it's just some text files. 

Here's another great example of proper license design: [The SBCL license](https://github.com/sbcl/sbcl/blob/master/COPYING). 
Everything is clear and straightforward.

**Comment by krpors** [comment]
I've had some time to read this whole 'discussion' and I have come to a few things. I've only taken the discussion **in this issue** in mind. I discarded everything else such as the Twitter posts, geopolitical issues or ideals whether it be Russia or Ukraine, or @5HT's blogpost(s) when forming my opinion.

1. @AlexZolcman's goal only seems to be that things are properly licensed regarding code written by others (in my case, MIT license). I think this is a very fair point.
2. @5HT seems to be overly 'hostile' when asked to license the source code correctly.

I don't have the time, money or the interest to pursue this further. I just wanted to make software which is helpful in any way. If you use `hx` for whatever, that's awesome. If my code is of any help, that's great as well. Adhere to the license, and then we are all good.

In any case, thanks for the heads-up, and thanks for using my software.

Peace with you all, stay safe.

**Comment by 5HT** [comment]
By saying `geopolitical issues` to `war` means you have chosen the side.

**Comment by 5HT** [comment]
> I never wished other people dead.
This is false.
![5269390398327994759_109](https://user-images.githubusercontent.com/144776/173181515-b2274899-0f7c-4077-bd48-41c91340d082.jpg)

**Comment by 5HT** [comment]
Btw, about being stolen. Do you know Russian Flag was stolen by Peter I from Netherlands?

**Comment by Borschemancer** [comment]
@5HT, it seems to me extremely disgraceful to justify the blatant copying of “hx” contributor’s work with the excuse of wartime on the territory of your homeland.

In these hard times, many of your fellow citizens have no access to water and food, they are dying at the front, while you are PRing and stealing other people’s code using the homeland for your own low and despicable gains.

By your behavior you only  bring shame to your country.

It's remarkable that first you ignore the author's will, according to which the “hx” project is licensed under the MIT license, which means it must be distributed and used in other projects in a strictly defined (by license) way, then, after his legitimate remarks, you start blatant hate speech in his direction. 

I am not even talking about how many intolerable curses, false, unfounded accusations I hear in my address.

How furiously you tried to avoid the proper licensing of “your” project “be” clearly shows your dishonest intentions. 

> I gave you credits from the very beginning without even finished the project. The fact that you implying me that I did something not correctly is insane. 

The “be” didn't have proper licensing and correct authorship neither from the beginning, when you just gave a link to the “hx” in the README.md, nor when you added the license texts to the directory. I've written about this above: it's just text, without any formal impact. Today the text is one, tomorrow you'll change it to whatever you want.

**Comment by AlexZolcman** [comment]
@5HT, it seems to me extremely disgraceful to justify the blatant copying of “hx” contributor’s work with the excuse of wartime on the territory of Ukraine.

In these hard times, many of your fellow citizens have no access to water and food, they are dying at the front, while you are PRing and stealing other people’s code using the homeland for your own low and despicable gains.

By your behavior you only  bring shame to your country.

It’s remarkable that first you ignore the author’s will, according to which the “hx” project is licensed under the MIT license, which means it must be distributed and used in other projects in a strictly defined (by license) way, then, after his legitimate remarks, you start blatant hate speech in his direction. 

I am not even talking about how many intolerable curses, false, unfounded accusations I hear in my address.

How furiously you tried to avoid the proper licensing of “your” project “be” clearly shows your dishonest intentions. 

> I gave you credits from the very beginning without even finished the project. The fact that you implying me that I did something not correctly is insane. 

The “be” didn’t have proper licensing and correct authorship neither from the beginning, when you just gave a link to the “hx” in the README.md, nor when you added the license texts to the directory. I’ve written about this above: it’s just text, without any formal impact. Today the text is one, tomorrow you’ll change it to whatever you want.

**Comment by 5HT** [comment]
Sue me for putting license in text files.

**Comment by AlexZolcman** [comment]
> This is the first incident in my entire Github career taking into account that I already produced a lot of software.

You simply stole most of “your” projects from other people by erasing their authorship. 
All your achievements are the creation of landing pages and further PR of these projects as your work. 
You just haven't met people willing to stand up for justice until now.

> I made a tons of forks with perfect feed-backs from authors and announcements.

So in the case of “hx”, if I had not directly pointed out the fact of license violation the author would not have noticed anything.

> I'm considering this thread as a speech platform given for a violent ruscist. 

Unlike you, I didn't say a single violent word.

> russians started stalking me, and only after full invasion

Let me remind you, on February 28 you [erased](https://github.com/groupoid/anders/commit/5f9485e123e98be7180d0f0d66a2553e44da9b62) all references to the author of Anders from everywhere, [called him your slave](https://web.archive.org/web/20220303111304/twitter.com/infinitystack/status/1499341999039782913) ([translation](https://user-images.githubusercontent.com/31402514/158180186-fd05bd33-707f-43ea-b3da-3920ac4dca45.jpg)), expressed [your desire to break his skull with a crowbar](https://user-images.githubusercontent.com/103067351/173191137-612d6659-393c-4413-aa4c-beb0c72be0bf.png) ([translation](https://user-images.githubusercontent.com/103067351/173191163-1279a125-0c54-4f0b-820f-7bceb09e4f64.jpg)) and then [were going to write a false denunciation to the Federal Security Service](https://twitter.com/n2otech/status/1512586527968305156) ([archived](https://web.archive.org/web/20220611140522/https://twitter.com/n2otech/status/1512586527968305156)).

And all this is a reaction to a fair defense of authorship.

> I would never promote hx author again. 

How does promotion have anything to do with anything? 
It's about respecting the author's legal rights to HIS OWN WORK.

**Comment by 5HT** [comment]
I promise I will break his skull.

**Comment by 5HT** [comment]
Now I promise I will break his skull. He caled me khohol explaining that in his village everybody is doing so, so I will break his skull as we usually do this to people who intentionally keep saying khohol into the face in our village. According to your friend's logic. You may also stop using my friend because your language clearly indicated that your friend equals you. Actually I'm talking to anonymous russian account created after russian full scale invasion to Ukraine.

Authorship was not removed. Just expelling for ruscism and license change. You already lost your license war. No matter how many shit you can put into random Github repos. I already gave my answer in this blog: https://tonpa.guru/stream/2022/2022-04-10%20Russian%20War%20against%20Groupoid%20Infinity.htm

If your friend is so young that he doesn't understand how to talk to people, I'll teach him.

For me any russian is slave as they brought fascism to their country and for 20 years were preparing and supporting the incoming war against Ukraine. For the entire life of my academical and enterprise career never seen educated, intelligent russian. Simple question "To whom belongs the Crimea?" clearly removes the veil of the true face of russian fascism on any of them.

I'm still considering this thread as a tribune for humiliating Ukrainians or at least me personally. Is this @5HT support channel? Or we can transform this feed into a photo stream of russian crimes in Ukraine?

**Comment by 5HT** [comment]
As our non-violen guy is trying to bring skulls to this thread I have a couple great pictures of russian dead soldiers.

**Comment by 5HT** [comment]
As our non-violent guy is trying to bring skulls to this thread I have a couple great pictures of russian dead soldiers. Just for him to imagine his future after next russian mobilization. And I will do this by hands of russian government. Actually his thinking will bring him to the place where this is going to happen.

**Comment by AlexZolcman** [comment]
Stop making up false accusations. I understand you have no excuse for your own behavior, so you start making blatant baseless slander. How many good people in the opensource community have you trashed just because they pointed out objective problems in your behavior? 

Everyone has always treated you with respect, but you took unfair advantage of someone else's kindness and simply stole the results of other people’s work and research. This has happened many times throughout your career.

And now you are using disastrous situation of your country for your illegal actions.

> If your friend is so young that he doesn't understand how to talk to people, I'll teach him.

In this issue you have totally demonstrated that you are unable to maintain a constructive dialog.

Your caveman belief in collective responsibility really blows my mind. What kind of ethics, what kind of intelligent behavior are you talking about?

> As our non-violent guy is trying to bring skulls to this thread I have a couple great pictures of russian dead soldiers. 

I want to repeat that geopolitics has absolutely nothing to do with this incident. 
There is an objective breach of license on your part, and all I ask is justice.

I understand the situation in which you are faced, but it can't change the fact that you are a thief. It can't change the fact that you wish another person dead just because you want to steal his project.

**Comment by 5HT** [comment]
![image](https://user-images.githubusercontent.com/144776/173232063-9211512b-e5e5-4737-8854-3c6b01860abc.png)

**Comment by 5HT** [comment]
You should apply application to Russia Today 👍

**Comment by AlexZolcman** [comment]
It seems to me that working as a mendacious propagandist passes more for you, @5HT.

You have all the qualities for it: a complete lack of morality and any principles at all (your willingness to kill a person for your benefit speaks clearly about this), adaptability to all conditions, and, just as importantly, arrogance and immeasurable self-love (and this man calls himself a Buddhist!). 

Your professional skills as a programmer and mathematician, unfortunately, leave much to be desired. 

It's pretty embarrassing to read your tweets about your “deep” knowledge of low-level programming. 

If one looks at your two “fully functioning” disassemblers, which, as you say in your twitter, you wrote in three days, one finds that your [disassembler for the 8086](https://github.com/asmedit/dasm-intel) supports only four (!) opcodes instead of the 45 you claimed (although in fact, the 8086 has more than a hundred instructions). And you haven't even begun to write a [disassembler for ARM](https://github.com/asmedit/dasm-arm).

In turn, your obscure posts about mathematics and type theory, with your extensive use of familiar (to you) mathematical terms and references to psychoactive substances, only impress people unfamiliar with mathematics, but only embarrass people who are familiar with it.

Overall, if one looks closely at all your activity, one can conclude that your skills are mostly limited to basic frontend development and graphic design. 
And it' s perfectly clear from your commits that you've been doing to the projects you stole.

Usually, these commits are very small and there are a lot of them. 
You do this to make an illusion of your big contribution to the projects.

Your work on these projects, for the most part, is the landing page layout, logo design. 
In addition, sometimes you change the names of functions in some files, rearrange the order of lines of code, in order to hide the fact of theft. 

Of course, for the most part, you don't understand how code works.
It seems to me, in some cases you haven't even read the code of your stolen projects.

This is easily evidenced by the fact that those projects that you have appropriated to yourself do not developed further in any way.

As an example, let's look at the notorious Anders typechecker, which you say you wrote entirely by yourself, while “your russian slave” only made minor edits. 

So, I spent a couple of days messing around with the version of Anders from your repository and proved the existence of bottom in a somewhat unsophisticated way:

```
module false where

import lib/foundations/univalent/iso

option pre-eval false

def rec₂ (A : U) (a b : A) : 𝟐 → A := 
    ind₂ (λ (_ : 𝟐), A) a b

def not := 
    rec₂ 𝟐 1₂ 0₂

def not-not := 
    ind₂ (λ (x : 𝟐), Path 𝟐 (not (not x)) x) (<_> 0₂) (<_> 1₂)

def boolEqBool := 
    isoPath 𝟐 𝟐 not not not-not not-not

def T : Path 𝟐 (idfun″ 𝟐 (idfun″ 𝟐 1₂)) 0₂ :=
    <i> transp (<j> hcomp U (-i ∨ i ∨ -j ∨ j)
                    (λ (k : I), [(i = 0) → boolEqBool @ (k ∧ j), (i = 1) 
                                    → 𝟐, (j = 0) → 𝟐, (j = 1) → 𝟐]) 𝟐) 0 0₂

def G (x : 𝟐) : Path 𝟐 (idfun″ 𝟐 x) x :=
    <i> (idfun=idfun″ 𝟐 @ -i) x

def R : Path 𝟐 0₂ 1₂ :=
    kan 𝟐 (idfun″ 𝟐 (idfun″ 𝟐 1₂)) (idfun″ 𝟐 1₂) 0₂ 1₂ T (G 1₂) (G (idfun″ 𝟐 1₂))

def f : 𝟐 → U := 
    ind₂ (λ (_ : 𝟐), U) 𝟏 𝟎

def g : 𝟎 := 
    subst 𝟐 f 0₂ 1₂ R ★
```

If you run the code above in the version of Anders [from the repository of the real author](https://github.com/forked-from-1kasper/anders/), it will not pass typechecking, you can check yourself. Tell me please, how come that “your Russian slave” adding features, fixing bugs, while you adjust HTML files and adding a photo of Anders Mortberg in README? Maybe it's because your entire "contribution" to Anders typechecker [is mindless code reformatting](https://github.com/groupoid/anders/commit/1d5c12a76ae966f09a9d8ebee6b54e7dcff28505)?

**I would like to point out that any attempts you might make to fix this bug by copying and pasting code from the real repository of [Anders project](https://github.com/forked-from-1kasper/Anders) won't go unnoticed**. And you won't be rescued by your favorite tricks like renaming functions and reformatting code.

You could also try doing a "force push" from the @forked-from-1kasper repository, but that won't go unnoticed either. Your repository is forked by several people, and your "commits" are [archived](https://web.archive.org/web/20220615171239/https://github.com/groupoid/anders/commits/). 

So, such an action will only confirm the act of your theft.

Another option is that you hire someone to fix the bug for you. 
I'm sure you're ready to pay any amount of money just to maintain your appearance as a "top programmer".

I won't write much about your contribution to the Anders library, except to say that I find it very revealing that most of the things (pretty elementary) you couldn't prove (like [1](https://github.com/groupoid/anders/commit/29867ca2fd958396201704cdd0dab6ff051f0cec), [2](https://github.com/groupoid/anders/commit/c12e6e102a2ecded1686d403ae621ae0495fafbb)) were then [proved](https://github.com/forked-from-1kasper/anders/commit/2c405465098df6347bcbda0342df3c0043a1856b) by "your slave". Not to mention the many occasions when your [terms](https://github.com/groupoid/anders/commit/63d49d6af9fe88da84d325cd09ee3ce606d9f0f6#diff-8de16b51482102e614dcca863973a1864edb16158552db5c9a3b7de894ddfeacR259) were, to say the least, [not the most elegant](https://github.com/groupoid/anders/commit/ca92c8f5a1a9a224d5d2a56ac41183879436c685).

In conclusion, I would like to question how hard it is to live, knowing deep down that all your achievements are in fact delusional?

And think about the fact that ordinary, humble people suffer from your malicious actions, which are aimed at maintaining the illusion of your total superiority in the open source and type theory community. People like the author of hx, like @forked-from-1kasper, whom you were willing to painfully kill, people like Jonathan Sterling, whom you sincerely hated purely out of envy. 

Tell me, doesn't it embarrass you when you talk about yourself as the owner of a "pocket corporation"? When you say, that your web frameworks currently power half of the infrastructure in Eastern Europe? 

Many people realize who you really are, and for those who don’t, sooner or later find out the truth. 
Lies are very hard to maintain for a long time. 

I don't think your way is going to lead to anything good. Look, maybe you should start reading those Buddhist books you've been buying to show off on social media? Even though it's really tough, I don't think it's ever too late to get out of the world of self delusion.

**Comment by AlexZolcman** [comment]
To my deepest regret, @5HT instead of fixing the objectively present bug in that version of the Anders typchecker that he hijacked, he again only cursed me and then deleted the issue. 

https://archive.fo/S7TjD

His [reaction and further attempts to hide the existence of this bug](https://github.com/groupoid/anders/issues/1) only only confirm his absolute incompetence.
