### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [krpors/hx#23]
Would you like to add more error handling for return values from functions like the following?
* [fclose](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream") ⇒ [editor_writefile](https://github.com/krpors/hx/blob/b6ccdbc58caba9a733a662eb84a8b2b7c90853ee/editor.c#L183)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [editor_newfile](https://github.com/krpors/hx/blob/b6ccdbc58caba9a733a662eb84a8b2b7c90853ee/editor.c#L95)
* [sigaction](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action") ⇒ [main](https://github.com/krpors/hx/blob/b6ccdbc58caba9a733a662eb84a8b2b7c90853ee/hx.c#L157)

**Comment by krpors** [comment]
I _suppose_ I could. Have you encountered issues with these calls failing in `hx`, perchance?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by krpors** [comment]
I've added some error checking here and there. Please check [the diff here](https://github.com/krpors/hx/compare/develop...feature/23-completion-error-handling). If there are things missing or you have a different take on error handling, send me a line and I can check it out.

**Comment by elfring** [comment]
>… or you have a different take on error handling, …

:thought_balloon: Would you become interested in [aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by krpors** [comment]
I know AOP from Java (AspectJ and Spring cruft). I'm not sure if I would want to incorporate that in this utility though, it sounds a bit excessive for a (hobby) project of this format.

**Comment by elfring** [comment]
>I know AOP from Java (AspectJ and Spring cruft).

This is good to know.


>I'm not sure if I would want to incorporate that in this utility though, …

:thinking: Would you like to [reuse any known functionality](https://www.aspectc.org/ "Software development with AspectC++")?

**Comment by krpors** [comment]
As I said, this hobby project of mine is too small IMHO to make use of AOP. Thanks for the heads up though, I did not know that AspectC was a thing.

**Comment by elfring** [comment]
>As I said, this hobby project of mine is too small IMHO to make use of AOP.

I am trying to present an other development view also for the usage of aspect-oriented programming.

Are you aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns?

**Comment by krpors** [comment]
I merged the branch into develop. If there are any other changes which should improve functionality or safety, I recommend making a PR instead. Thanks!

**Comment by elfring** [comment]
:eyes: [Further update candidates were left over](https://github.com/krpors/hx/blob/e592e8c07577b003619ff1c5df431d1b8c0b68bb/editor.c#L102 "Update candidate: editor_newfile()").

:thought_balloon: It is just safer to [handle also more “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?
