### ISSUE TITLE
Doxygen style comments used in project, but do not conform to doxygen format confusing syntax highlighting.

### ISSUE THREAD

**Issue by EliteTK** [krpors/hx#8]
The comments in the project use /** which is used by tools like doxygen to distinguish between normal comments and comments which are designed to be used for generating documentation. This can confuse certain syntax highlighting and if the project ever wishes to switch to doxygen (unlikely because this is not a library but who knows) then this will need to be done anyway.

Additionally some multi line comments are done using C99 style `//` comments. It might be worthwhile to switch to using one style throughout the project if the comments are to be changed to normal `/*` comments.

**Comment by krpors** [comment]
I sort of borrowed this style from Java (javadoc style), and a combination of what's mentioned in the [Linux Kernel CodingStyle](http://lxr.free-electrons.com/source/Documentation/CodingStyle#L535). So I tend to write any function documentation (usually in the header files) using `/*` or `/**`, and single (or two) line comments using the C99 `//` style.

**Comment by EliteTK** [comment]
I can't see `/**` comments mentioned in the kernel style docs. And I don't think I've ever seen them used in the kernel outside of doxygen (same as javadoc) style comments which follow the doxygen / javadoc format. e.g.: http://lxr.free-electrons.com/source/include/linux/hid.h#L639

**Comment by EliteTK** [comment]
Examples from doxygen documentation:

https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html

The other option is to switch to actual doxygen style documentation, I certainly would be happy to provide a patch doing this in all the header files.

**Comment by krpors** [comment]
I guess just to be consistent, changing the doxygen style `/**` to `/*` would be OK. I'm not planning to make it a library anyway :)
